---
author: "Sean Anderson, Paul Regular"
title: "Filling the gaps: using simulation to test model-based solutions to survey problems"
---

# Participants

Sean Anderson
Paul Regular
Alex Hanke
Brooke Biddlecombe
Dan Ricard
Daniel Duplisea 
Elisabeth Van Beveren
Fatemeh Hatefi
Hannah Munro
Ian Perry
Jordan Ouellette-Plante
Kevin Hedges
Kotaro Ono
Kyle Gillespie
Laura Bianucci
Liza Tsitrin
Marie-Julie Roux
Mark Billard
Mathieu Boudreau
Meghan Burton
Michelle Fitzsimmons
Michelle Greenlaw
Philina English
Quang Huynh
Rajeev Kumar
Ross Tallman
Shani Rousseau
Shannon Obradovich
Stephane Gauthier
Tom Bermingham
Wayne Hajas
Xinhua Zhu


# The challenge

A: Including covariates. Does including a covariate (depth) increase precision, estimate the right depth relationship, and maintain an unbiased index with greater precision compared to not including any covariates (or any one of these questions)? Are there scenarios where that is or isn't the case?

B: Changes to spatial coverage from year to year. E.g. If part of the survey (e.g. multiple strata, half the survey area) is missed in some years, can the model recover the index? This includes "hole" filling.

C: Does using an AR1 spatiotemporal field (without factor levels for years) constrain the model too much and result in hyperstability?

D: If the catchability of a survey changed along the time series, say the gear was changed and there was one year of calibration overlap, could the model estimate the catchability (q) offset and provide unbiased estimates of the population available to the contemporary survey as if those gear were used the whole time?

E: If two surveys with different catchabilities are conducted in parallel at neighbouring divisions, could a model 'stitch' these surveys together to provide a unified estimate of the population?

F: Are there survey designs that result in the model-based index being more or less precise than the design based index?

G: Can we obtain an index at age using a geostatistical model?


# Approach taken

# Key points discussed

# Successes

# Challenges

# How far did we get?

# Next steps

# Expected outcomes
